BASE_ERRORS: list[str]

class NexumError(Exception): ...
class NexumRuntimeError(NexumError, RuntimeError): ...
class NexumTypeError(NexumError, TypeError): ...
class NexumValueError(NexumError, ValueError): ...
class NexumSyntaxError(NexumError, SyntaxError): ...
class NexumKeyError(NexumError, KeyError): ...
class NexumIndexError(NexumError, IndexError): ...
class NexumAttributeError(NexumError, AttributeError): ...
class NexumFileNotFoundError(NexumError, FileNotFoundError): ...
class NexumZeroDivisionError(NexumError, ZeroDivisionError): ...

__all__: list[str] = [
    "NexumError",
    "NexumRuntimeError",
    "NexumTypeError",
    "NexumValueError",
    "NexumSyntaxError",
    "NexumKeyError",
    "NexumIndexError",
    "NexumAttributeError",
    "NexumFileNotFoundError",
    "NexumZeroDivisionError",
]
